services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${MAIN_DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5

  db-init:
    build: .
    command: python -c "from src.db_init.db_setup import create_database, create_tables; create_database(); create_tables()"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  app:
    build: .
    depends_on:
      db-init:
        condition: service_completed_successfully
    env_file: .env

  dbt:
    build:
      context: .
      dockerfile: dockerfile.dbt
    depends_on:
      app:
        condition: service_completed_successfully
    env_file: .env