version: 2

models:
  - name: fact_ratings
    columns:
      - name: rating_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
      - name: book_id
        tests:
          - not_null
      - name: rating
        tests:
          - accepted_values:
              arguments:
                values: [0,1,2,3,4,5,6,7,8,9,10]