CREATE OR REPLACE TRIGGER trg_audit_authors
AFTER INSERT OR UPDATE OR DELETE ON dim.dim_authors
FOR EACH ROW EXECUTE FUNCTION func_audit_log();

CREATE OR REPLACE TRIGGER trg_audit_publishers
AFTER INSERT OR UPDATE OR DELETE ON dim.dim_publishers
FOR EACH ROW EXECUTE FUNCTION func_audit_log();

CREATE OR REPLACE TRIGGER trg_audit_books
AFTER INSERT OR UPDATE OR DELETE ON dim.dim_books
FOR EACH ROW EXECUTE FUNCTION func_audit_log();

CREATE OR REPLACE TRIGGER trg_audit_users
AFTER INSERT OR UPDATE OR DELETE ON dim.dim_users
FOR EACH ROW EXECUTE FUNCTION func_audit_log();

CREATE OR REPLACE TRIGGER trg_audit_ratings
AFTER INSERT OR UPDATE OR DELETE ON fact.fact_ratings
FOR EACH ROW EXECUTE FUNCTION func_audit_log();